// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh4Ont0i7NMxaA8Ntoddktfqp6fenxbZ8',
    appId: '1:305180371109:android:bf0f89e78fa484e239854c',
    messagingSenderId: '305180371109',
    projectId: 'baliraja-11a9d',
    storageBucket: 'baliraja-11a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzMBSPSFSk6x-sn6lLn2rE8IR_6X0S4wY',
    appId: '1:305180371109:ios:aff18635c2825fc639854c',
    messagingSenderId: '305180371109',
    projectId: 'baliraja-11a9d',
    storageBucket: 'baliraja-11a9d.firebasestorage.app',
    iosClientId: '305180371109-j0cq59u7qaveouc5o9k6sn3nhq644ad5.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzMBSPSFSk6x-sn6lLn2rE8IR_6X0S4wY',
    appId: '1:305180371109:ios:aff18635c2825fc639854c',
    messagingSenderId: '305180371109',
    projectId: 'baliraja-11a9d',
    storageBucket: 'baliraja-11a9d.firebasestorage.app',
    iosClientId: '305180371109-j0cq59u7qaveouc5o9k6sn3nhq644ad5.apps.googleusercontent.com',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZGkzyaX0mavmkcGWeydOXkOEMw1-YVA',
    appId: '1:305180371109:web:0886b5fb04a9231739854c',
    messagingSenderId: '305180371109',
    projectId: 'baliraja-11a9d',
    authDomain: 'baliraja-11a9d.firebaseapp.com',
    storageBucket: 'baliraja-11a9d.firebasestorage.app',
    measurementId: 'G-HEP0JQ9BCT',
  );

}